### ISSUE TITLE
本地图片刷新问题

### ISSUE THREAD

**Issue by yuan488** [zyujs/setu_mix#1]
使用setu fetch拉入图片，似乎会把原来的图片删除，因此本地图片永远只有20张

**Comment by zyujs** [comment]
不可能,有本地缓存的图片会跳过下载

**Comment by yuan488** [comment]
![-b78366bd7998e79](https://user-images.githubusercontent.com/69119229/96357016-7f7a0800-1128-11eb-966d-8448066ca711.png)

**Comment by zyujs** [comment]
请发log

**Comment by yuan488** [comment]
![IMG_20201018_100841](https://user-images.githubusercontent.com/69119229/96357126-f1068600-1129-11eb-838e-decfbc2c8fca.jpg)

**Comment by zyujs** [comment]
你的服务器图片下载速度快的不正常,不清楚你的服务器是否在境外,建议在服务器用浏览器或者wget访问上图图片网址.
另外可以尝试删除res中的setu_mix缓存目录并重启hoshino重新尝试缓存.

**Comment by zyujs** [comment]
确实是bug, 已经找到了问题原因, 等我修复一下

**Comment by yuan488** [comment]
感谢😘😚😗😙

**Comment by zyujs** [comment]
是在lolicon模块中错误的使用了acggov的mode，更新一下插件就可以了
